{
 "title": "Pi Hole",
 "tags": [
  "pi-hole",
  "app"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "clients",
    "label": "Clients",
    "query": "label_values(pihole_all_queries, client)"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Queries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "pihole_dns_queries_today" }
   ]
  },
  {
   "title": "Queries blocked",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "pihole_ads_blocked_today" }
   ]
  },
  {
   "title": "Percent blocked",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "expr": "pihole_ads_percentage_today" }
   ]
  },
  {
   "title": "Domains blocked",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "pihole_domains_being_blocked" }
   ]
  },
  {
   "title": "Forwarded Queries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "pihole_queries_forwarded" }
   ]
  },
  {
   "title": "Gravity Last Updated",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - pihole_gravity_last_updated"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "pihole_unique_clients" },
    {}
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "pihole_status" }
   ]
  },
  {
   "title": "Top clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pihole_top_sources", "legendFormat": "{{client}}" }
   ]
  },
  {
   "title": "Top queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pihole_top_queries", "legendFormat": "{{domain}}" }
   ]
  },
  {
   "title": "Top Ads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pihole_top_ads", "legendFormat": "{{domain}}" }
   ]
  },
  {
   "title": "Forward Destinations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "pihole_forward_destinations{resolver!=\"local|::1\"}",
     "legendFormat": "{{resolver}}"
    }
   ]
  },
  {
   "title": "Query Types",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "pihole_query_type", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Reply Types",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pihole_reply_cname", "legendFormat": "CNAME" },
    { "expr": "pihole_reply_ip", "legendFormat": "IP" },
    { "expr": "pihole_reply_nodata", "legendFormat": "NODATA" },
    { "expr": "pihole_reply_nxdomain", "legendFormat": "NXDOMAIN" }
   ]
  },
  { "title": "Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "$clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "repeat": "clients",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pihole_all_queries{client=~\"$clients\"}",
     "legendFormat": "{{ domain  }}"
    }
   ]
  }
 ]
}